#!/bin/bash
source ${OPENSHIFT_REPO_DIR}/.openshift/.leinrc

cd ${OPENSHIFT_REPO_DIR}
mkdir -p deployments
${OPENSHIFT_DATA_DIR}/lein do clean, immutant war -o deployments -n ROOT

#start of funky changes

#cd ${OPENSHIFT_DATA_DIR};

#git clone https://github.com/FalseProtagonist/graphagora.git;

